chicommons/maps

client/src/App.css
client/src/App.js
client/src/components/Add.jsx
client/src/components/CoopTypes.jsx
client/src/components/Country.jsx
client/src/components/Flash/index.js
client/src/components/Input.jsx
client/src/components/NavBar.css
client/src/components/NavBar.js
client/src/components/Province.jsx
client/src/containers/FormContainer.jsx

Resolves Style Directory App according to Chicommons style guide #10

updated color for buttons and headers

---

client/src/components/CoopTypes.jsx
client/src/components/Country.jsx
client/src/components/Input.jsx
client/src/components/Province.jsx
client/src/containers/FormContainer.css
client/src/containers/FormContainer.jsx

Created class for required form inputs and used CSS to add red asterisk after each label. No changes to the validation or requirements logic.

Adding asterisks to Coop form

---

client/src/containers/FormContainer.jsx

Ned to be able to add/edit "Enabled" (Included) coop field

enabled button above submit

---

client/src/App.js
client/src/components/NoCoordsSearch.jsx

Created NoCoordsSearch.jsx component and routed to - .../nocoords

No Coordinates search Draft 1

---

web/directory/management/commands/parse_coop_csv.py

This PR contains the minimal changes necessary to parse the new .csv file.
The new .csv file does not have an 'ID' column. I wrote a small work around, since the 'ID' is the same as the row number. I do think it's better to include an 'ID' column in the file instead.

Adjustments for the new csv file.

---

web/directory/management/commands/parse_coop_csv.py

Solving issue #38; allowing import of addresses for entities which have no lat/lon.

Allowing entities with no lat/lon

---

client/src/App.js
client/src/components/AdvancedSearch.jsx
client/src/components/NavBar.js

Hi @laredotornado  - Here's my initial work on building the Advanced Search component page.
I used comments to note places where I borrowed code from other components. For example, the renderSearchResults() method is exactly the same as the renderSearchResults() method in the Search component. Would you like me to work on refactoring this so that repeated code is shared across components?
Happy to schedule a call if it's easier to discuss your feedback over a call than over email!
Thanks,
Elena

resolves #13 - Advanced Search component page

---

client/src/App.js
client/src/components/DirectoryAddUpdate.jsx
client/src/containers/FormContainer.css

Pull request for the first draft of the Directory addition form.

Directory form 1st draft for comments

---

client/src/components/DirectoryAddUpdate.jsx

✔️ Reason for submission should be a dropdown add new or update existing record
✔️ Address, city, state and zip should be on one line in wide screen 
✔️ County, country and address public should be on one line in wide screen

Issue 70 updates, cosmetic changes

---

client/public/index.html

Issue 71: Changed title to CoOp map

---

client/src/components/DirectoryAddUpdate.jsx

This is the current draft of adding more bootstrap breakpoints based on notes from the last meeting I was part of. I am having trouble with figuring out what looks best with the fields that have longer labels. Unfortunately it does not seem like there's much we can do when the labels have a lot of text, but possibly there might be someone with some more bootstrap experience who may be able to advise if possible. Let me know how it looks.

Issue 84: Bootstrap form breakpoints and layout update

---

client/src/components/Search.jsx

Returns search result link to https://prod.chicommons.coop/directory-additions-updates/{id}

Issue 77: Change link location where advanced search results

---

client/src/components/DirectoryAddUpdate.jsx
client/src/components/DropDownInput.jsx
client/src/components/Map.js
client/src/components/NavBar.css
client/src/components/NavBar.js
client/src/containers/Map.css

Shortened directory form placeholder text for multiple items per Steve's request during 7/1/21 meeting. Checked if this was a potential accessibility issue but it looks like it's alright.

Placeholder text

---

client/src/components/NavBar.js

Removed bad location from navbar per https://github.com/chicommons/maps/issues/89

Issue 89: Removed Bad Location from navbar

---

client/src/components/DirectoryAddUpdate.jsx
client/src/services/CoopService.jsx

Updates to error handling for submit and loading existing entity

Error handling

---

client/src/components/Search.jsx

Moved street, city, postal code onto one line. Moved county, state, enabled onto one line.

Issue-110: Added breakpoints to search at 1140, 992, 768 px.

---

client/src/App.css
client/src/components/DirectoryAddUpdate.jsx
client/src/index.css

Per Steve's request, this is functionality to route the user to the search form after successfully submitting form for an already existing entity.

Route form on submit

---

client/src/App.css
client/src/index.css

The width of the inner auth div was stretching too wide on smaller screen sizes. I commented out the media query that was causing the issue. I'm not sure if it was to be deleted or updated to work differently in the future, so I didn't delete it.

Commented out auth-inner media query for responsiveness

---

client/src/components/AlertProvider.jsx
client/src/components/DirectoryAddUpdate.jsx
client/src/utils/constants.jsx

Here is an attempt at the alert message on a successful form submission. I wasn't able to test on the most current repo, so please let me know if this isn't working properly. Thanks!

Successful submit alert draft 1

---

client/src/containers/FormContainer.css
web/directory/serializers.py
web/directory/views.py

Also changed font size for error messages to 16px to match other form text.
I think Atom automatically cleaned the extra whitespaces, but the only real change here is in serializers.py 342-388

combined form validation to one step

---

client/src/containers/MapContainer.css

For Issue #137  - Adjusts height of map on large screen size so the footer comes into view.

Bring up footer on large screen size

---

client/package.json
client/src/App.test.js
client/src/__tests__/search.test.js
client/src/components/Search.jsx

I added an initial test to check if the message "Loading..." appears after someone hits "Submit" on the search form.

Add initial user event tests

---

client/src/components/DirectoryAddUpdate.jsx

Addresses [#183 ](https://github.com/chicommons/maps/issues/183)and [#184](https://github.com/chicommons/maps/issues/184)
Changes to `fetchCoopForUpdate` on `DirectoryAddUpdate.jsx` to correctly set state for coop email and entity types.

Directory update form updates (issues 183 & 184)

---

client/src/components/Search.jsx

Search form multi select dropdown fix to match requested behavior

---

client/src/components/Login.jsx
client/src/components/NewUser.jsx

This should have error handling working for both the login and signup forms. 
I also tweaked the JSX of the form to match the style of our other forms.

adds error handling for login and signup forms

---

web/directory/management/commands/parse_coop_csv.py
web/directory/services/location_service.py

Code created to make sure addresses, phone numbers, and email addresses are not publicly displayed if permission is not given.

Enable privacy flags

---

client/src/components/Search.jsx
client/src/components/Spreadsheet.jsx
web/directory/serializers.py

* Adds phone, email, and types to the search serializer
* Refactors query functions in spreadsheet component
* Sets column widths in spreadsheet 
* Adds the following data elements to the spreadsheet component
* Street number
* Route
* Raw address
* Latitude
* Longitude
* Locality ID
* State ID
* State code
* Country Id
* Country Code
* Entity types

Resolve #190 - spreadsheet horizontal scroll
